### ISSUE TITLE
Reported Accuracy

### ISSUE THREAD

**Issue by rahulvigneswaran** [zhangyongshun/BagofTricks-LT#13]
Can you confirm that the following splits are used for reporting the final accuracies in the paper?

CIFAR100-LT: Val Split
ImageNet-LT: Test Split
iNaturalist18: Val Split

Do all the earlier works follow the same, that is report final accuracies for CIFAR100-LT and iNaturalist18 only for validation splits and **not test split**s?

**Comment by zhangyongshun** [comment]
Yes,  all the earlier papers follow the same setting. The accuracies of CIFAR-LT and iNaturalist18 are only for validation splits. Moreover, the test set of  ImageNet-LT is the validation set of ImageNet (ILSVRC 12).
