### ISSUE TITLE
about Trick combinations

### ISSUE THREAD

**Issue by Ein027** [zhangyongshun/BagofTricks-LT#6]
Hello! Thanks for your contribution. I have such questions:
1. In the combination of IM & DRS with CAM-BS, At what stage is IM used? or both stage?
2. In  the fine-tuning after mixup training (Table 11), which epoch do you remove the mixup?
3. Is there some configs for the combination tricks ?

Thanks a lot ~

**Comment by zhangyongshun** [comment]
Thanks for your interest!
We have discussed the above questions by WeChat, and I will update the configs and corresponding results of the best trick combination in the next few days!
