### ISSUE TITLE
About ReMix

### ISSUE THREAD

**Issue by liming-ai** [zhangyongshun/BagofTricks-LT#8]
Hi @zhangyongshun ,

Thanks for your contribution, could you please tell me where is the code for ReMix?

**Comment by zhangyongshun** [comment]
Hi, the ReMix related codes are located at [this link](https://github.com/zhangyongshun/BagofTricks-LT/blob/aec4d9a552236c32231374b7b00fa5bf4208dae3/lib/core/combiner.py#L107), and this file also contains other mixup related methods, such as input mixup and manifold mixup.

**Comment by liming-ai** [comment]
Thanks a lot!
